name: fl_lib
description: "Flutter lib for common use cases."
version: 0.0.1
homepage: https://github.com/lppcg/fl_lib
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  app_links: ^6.1.1
  choice: ^2.3.2
  cloudflare_turnstile: ^3.2.1
  crypto: ^3.0.3
  dio: ^5.4.2+1
  encrypt: ^5.0.3
  extended_image: ^10.0.0
  file_picker: ^9.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.1
  flutter_markdown_latex: ^0.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  icloud_storage: ^2.2.0
  icons_plus: ^5.0.0
  image: ^4.2.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  local_auth: ^2.2.0
  locale_names: ^1.1.1
  logging: ^1.2.0
  markdown: ^7.2.2
  mime: ^2.0.0
  path_provider: ^2.1.3
  pretty_qr_code: ^3.3.0
  qr_code_dart_scan: ^0.9.0
  screenshot: ^3.0.0
  share_plus: ^10.0.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  window_manager: ^0.4.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  webdav_client:
    git:
      ref: v1.0.66
      url: https://github.com/lollipopkit/webdav_client
  computer:
    git:
      url: https://github.com/lollipopkit/dart_computer
      ref: v1.0.88

# dependency_overrides:
  # flutter_markdown_latex:
  #   path: ../flutter_markdown_latex

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  generate: true
